apiVersion: apps/v1
kind: Deployment
metadata:
  name: ossj00
  labels:
    app: ossj00
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ossj00
  template:
    metadata:
      labels:
        app: ossj00
    spec:
      containers:
        - name: ossj00
          image: sencream/ossj00:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
            requests:
              memory: "64Mi"
              cpu: "125m"
          ports:
            - containerPort: 3000
              name: ossj00
      tolerations:
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: ossj00
  labels:
    app: ossj00
spec:
  ports:
    - port: 5006
      targetPort: 3000
  selector:
    app: ossj00
  type: LoadBalancer

