apiVersion: apps/v1
kind: Deployment
metadata:
  name: ossj00
  labels:
    app: ossj00
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ossj00
  template:
    metadata:
      labels:
        app: ossj00
        tier: ossj00
    spec:
      containers:
        - name: ossj00
          image: sencream/ossj00:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: ossj00
---
apiVersion: v1
kind: Service
metadata:
  name: ossj00
  labels:
    app: ossj00
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: ossj00
    tier: ossj00
  type: LoadBalancer
